### ISSUE TITLE
JsonMappingException - Can not deserialize out of START_ARRAY token

### ISSUE THREAD

**Issue by alimazrae** [yafrica/coinbase-api-v2-java#2]
A response object for a list of accounts is throwing this error. Have looked at the code and can't see an issue with it.

Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of coinbase.api.v2.bean.response.ListCoinbaseAccount out of START_ARRAY token

**Comment by alimazrae** [comment]
Could not find the exact fault of the error. I have removed the List classes which extend AbstractCoinbaseResponse and instead return a List<T> object from the mapper, passing an isList boolean if a list needs to be returned. 

`if(isList){
            return COINBASE_MAPPER.convertValue(dataNode, COINBASE_MAPPER.getTypeFactory().constructCollectionType(List.class, classz));
        } else {
            return COINBASE_MAPPER.treeToValue(dataNode, classz);
        }`

I also had to change the values in bean files as the result was different from expected.

**Comment by yafrica** [comment]
I can see the issue, it is related to currency property.
It is fixed now.
You can still use my API, no problem. However, contact me if you make money with it.

Regards.
Yoan
